name: Publish to PyPI
on:
  push:
    paths: ["lrcup/__init__.py", "pyproject.toml"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lrcup
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.4"
        enable-cache: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        uv sync --locked
        uv pip install hatch
    - name: Build package
      run: uv run hatch build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1